import React from 'react';
import { expect } from 'chai';
import Enzyme, { shallow } from 'enzyme';
import ReactDOM from 'react-dom';
import { exportAllDeclaration } from '@babel/types';
import ScoreCard from '../components/content/ScoreCard/ScoreCard';

describe('ScoreCard', () => {
	it('renders without crashing', () => {
		const div = document.createElement('div');
		ReactDOM.render(<ScoreCard />, div);
		ReactDOM.unmountComponentAtNode(div);
	});
    
    it('should render the team name', () => {
        const wrapper = shallow(<ScoreCard/>);
        expect(wrapper.containsAllMatchingElements([
            <div>
				<table>
					<thead>
						<tr>
							<th>
								WEST ORANGE WARRIORS
							</th>
						</tr>
						<tr>
							<th>
								Bowler
							</th>
							<th>
								Game 1
							</th>
							<th>
								Game 2
							</th>
							<th>
								Game 3
							</th>
							<th>
								Series
							</th>
							<th>
								Running Total
							</th>
						</tr>
					</thead>
					<tbody>
						<tr>
							<td>
								Kimberly Hamilton
							</td>
							<td>
								195
							</td>
							<td>
								205
							</td>
							<td>
								230
							</td>
							<td>
								630
							</td>
							<td>
								630
							</td>
						</tr>
						<tr>
							<td>
								Kimberly Hamilton
							</td>
							<td>
								195
							</td>
							<td>
								205
							</td>
							<td>
								230
							</td>
							<td>
								630
							</td>
							<td>
								1260
							</td>
						</tr>
						<tr>
							<td>
								Kimberly Hamilton
							</td>
							<td>
								195
							</td>
							<td>
								205
							</td>
							<td>
								230
							</td>
							<td>
								630
							</td>
							<td>
								1890
							</td>
						</tr>
						<tr>
							<td>
								Kimberly Hamilton
							</td>
							<td>
								195
							</td>
							<td>
								205
							</td>
							<td>
								230
							</td>
							<td>
								630
							</td>
							<td>
								2520
							</td>
						</tr>
						<tr>
							<td>
								Kimberly Hamilton
							</td>
							<td>
								195
							</td>
							<td>
								205
							</td>
							<td>
								230
							</td>
							<td>
								630
							</td>
							<td>
								3150
							</td>
						</tr>
						<tr>
							<td></td>
							<td></td>
							<td></td>
							<td></td>
							<td></td>
							<td>
								3150
							</td>
						</tr>
						<tr>
							<td></td>
							<td></td>
							<td></td>
							<td></td>
							<td></td>
							<td>
								3150
							</td>
						</tr>
						<tr>
							<td></td>
							<td></td>
							<td></td>
							<td></td>
							<td></td>
							<td>
								3150
							</td>
						</tr>
						<tr>
							<td></td>
							<td></td>
							<td></td>
							<td></td>
							<td></td>
							<td>
								3150
							</td>
						</tr>
						<tr>
							<td></td>
							<td></td>
							<td></td>
							<td></td>
							<td></td>
							<td>
								3150
							</td>
						</tr>
					</tbody>
					<tfoot>
						<tr>
							<td>
								GrandTotal
							</td>
							<td>
								975
							</td>
							<td>
								1025
							</td>
							<td>
								1150
							</td>
							<td>
								3150
							</td>
							<td>
								3150
							</td>
						</tr>
						<tr>
							<td></td>
							<td></td>
							<td></td>
							<td>
								Bishop Moore
							</td>
							<td>
								+/-
							</td>
							<td>
								0
							</td>
						</tr>
					</tfoot>
				</table>
				<table>
					<thead>
						<tr>
							<th>
								BISHOP MOORE HORNETS
							</th>
						</tr>
						<tr>
							<th>
								Bowler
							</th>
							<th>
								Game 1
							</th>
							<th>
								Game 2
							</th>
							<th>
								Game 3
							</th>
							<th>
								Series
							</th>
							<th>
								Running Total
							</th>
						</tr>
					</thead>
					<tbody>
						<tr>
							<td>
								Player 1
							</td>
							<td>
								195
							</td>
							<td>
								205
							</td>
							<td>
								230
							</td>
							<td>
								630
							</td>
							<td>
								630
							</td>
						</tr>
						<tr>
							<td>
								Player 2
							</td>
							<td>
								195
							</td>
							<td>
								205
							</td>
							<td>
								230
							</td>
							<td>
								630
							</td>
							<td>
								1260
							</td>
						</tr>
						<tr>
							<td>
								Player 3
							</td>
							<td>
								195
							</td>
							<td>
								205
							</td>
							<td>
								230
							</td>
							<td>
								630
							</td>
							<td>
								1890
							</td>
						</tr>
						<tr>
							<td>
								Player 4
							</td>
							<td>
								195
							</td>
							<td>
								205
							</td>
							<td>
								230
							</td>
							<td>
								630
							</td>
							<td>
								2520
							</td>
						</tr>
						<tr>
							<td>
								Player 5
							</td>
							<td>
								195
							</td>
							<td>
								205
							</td>
							<td>
								230
							</td>
							<td>
								630
							</td>
							<td>
								3150
							</td>
						</tr>
						<tr>
							<td></td>
							<td></td>
							<td></td>
							<td></td>
							<td></td>
							<td>
								3150
							</td>
						</tr>
						<tr>
							<td></td>
							<td></td>
							<td></td>
							<td></td>
							<td></td>
							<td>
								3150
							</td>
						</tr>
						<tr>
							<td></td>
							<td></td>
							<td></td>
							<td></td>
							<td></td>
							<td>
								3150
							</td>
						</tr>
						<tr>
							<td></td>
							<td></td>
							<td></td>
							<td></td>
							<td></td>
							<td>
								3150
							</td>
						</tr>
						<tr>
							<td></td>
							<td></td>
							<td></td>
							<td></td>
							<td></td>
							<td>
								3150
							</td>
						</tr>
					</tbody>
					<tfoot>
						<tr>
							<td>
								GrandTotal
							</td>
							<td>
								975
							</td>
							<td>
								1025
							</td>
							<td>
								1150
							</td>
							<td>
								3150
							</td>
							<td>
								3150
							</td>
						</tr>
					</tfoot>
				</table>
            </div>
		])).to.equal(true);
    });})

